CREATE TABLE [dbo].[tblSalesLedgerEntry] (
    [SalesLedgerEntryID]          UNIQUEIDENTIFIER NOT NULL,
    [LedgerEntryTypeID]           UNIQUEIDENTIFIER NOT NULL,
    [SalesLedgerEntryDescription] NVARCHAR (100)   NOT NULL,
    [SaleAmount]                  NUMERIC(18,4)            NOT NULL,
    [FXSaleAmount]                NUMERIC(18,4)            NULL,
    [CurrencyID]                  UNIQUEIDENTIFIER NULL,
    [ExchangeRate]                NUMERIC (16, 4)  NULL,
    [CustomerDepartmentID]        UNIQUEIDENTIFIER NOT NULL,
    [BatchNumberLogID]            UNIQUEIDENTIFIER NOT NULL,
	[TransactionTaxAmount]		NUMERIC(18,4) NULL,
    [NoteID]                      UNIQUEIDENTIFIER NULL,
    [UpdatedBy]                   NVARCHAR (25)    NULL,
    [UpdatedDate]                 DATETIME         NULL,
    [CreatedBy]                   NVARCHAR (25)    NULL,
    [CreatedDate]                 DATETIME         NULL,
    [IsHistory]                   BIT              CONSTRAINT [DF__tblSalesL__IsAct__2DE6D218] DEFAULT ((1)) NOT NULL,
    [AccountingYear]              INT              NOT NULL,
    [AccountingPeriod]            Int          NOT NULL,
	[SalesPersonUserID] UNIQUEIDENTIFIER NULL,
	[SaleDate] DATETIME NULL,
    CONSTRAINT [PK_tblSalesLedgerEntry_1] PRIMARY KEY CLUSTERED ([SalesLedgerEntryID] ASC),
    CONSTRAINT [FK_tblSalesLedgerEntry_tblBatchNumber] FOREIGN KEY ([BatchNumberLogID]) REFERENCES [dbo].[tblBatchNumberLog] ([BatchNumberLogID]),
    CONSTRAINT [FK_tblSalesLedgerEntry_tblCustomerDepartment] FOREIGN KEY ([CustomerDepartmentID]) REFERENCES [dbo].[tblCustomerDepartment] ([CustomerDepartmentID]),
    CONSTRAINT [FK_tblSalesLedgerEntry_tblNote] FOREIGN KEY ([NoteID]) REFERENCES [dbo].[tblNote] ([NoteID]),
    CONSTRAINT [FK_tblSalesLedgerEntry_tblSalesLedgerEntryType] FOREIGN KEY ([LedgerEntryTypeID]) REFERENCES [dbo].[tlkpLedgerEntryType] ([LedgerEntryTypeID]),
    CONSTRAINT [FK_tblSalesLedgerEntry_tlkpCurrency] FOREIGN KEY ([CurrencyID]) REFERENCES [dbo].[tlkpCurrency] ([CurrencyID])
);

