
----cLEAR DATABASE DOWN 
----cLEAR DATABASE 1a DOWN 
--use [PrimeActsLIVE]
--delete from  AspNetRolePermission 
--delete from AspNetUserRoles 
--delete from AspNetUsers 
--delete from AspNetRoles 
--delete from  AspNetPermissions 
--delete from tblSalesAllocation
--delete from tblSalesInvoiceItem
--delete from tblSalesInvoice
--delete from tblSalesLedgerEntry
--delete from tblSalesAllocation
--DELETE From tblTicketItem 
--DELETE FROM tblTicket
--DELETE FROM tblConsignmentItem
--delete from tblConsignmentFile
--DELETE FROM tblConsignment
--delete from tblFile
--DELETE FROM tlkpCreditRating
--DELETE FROM tblProduce
--DELETE FROM tblMasterGroup
--DELETE FROM tblProduceGroup

--DELETE FROM tlkpVATRate
--DELETE FROM tlkpVATCode
--DELETE FROM tlkpPurchaseType
--DELETE FROM tlkpDespatchLocation
--DELETE FROM tlkpPorterage
--DELETE FROM tlkpPackWtUnit
--DELETE FROM tlkpCountry
--DELETE FROM tlkpPort
--DELETE FROM tlkpTransferType
--delete from tlkpStockLocation
--delete from tblSetupGlobal
--delete from tblSetupLocal
--delete from tgenSalesInvoiceNumber

--DELETE FROM tblSupplierBankAccount
--DELETE FROM tblSupplierContact
--DELETE FROM tblSupplierDepartmentLocation
--DELETE FROM tblSupplierDepartment
--DELETE FROM tblSupplierLocation
--DELETE FROM tblSupplier
--DELETE FROM tblCustomerBankAccount
--DELETE FROM tblCustomerContact
--delete from tblContact
--DELETE FROM tblCustomerDepartmentLocation
--delete from tblSalesLedgerEntry
--DELETE FROM tblCustomerDepartment
--DELETE FROM tblCustomerLocation
--DELETE FROM tblCustomer
--DELETE FROM tlkpCustomerType
--delete from tlkpLedgerEntryType
--DELETE FROM tblBankAccount
--DELETE FROM tblNote
--DELETE FROM tblDepartment
--delete from tblNominalLedgerEntry
--delete from tblNominalAccount
--delete from tblBatchNumberLog
--delete from tbldivision
--delete from tlkpCurrency
--delete from tblCompany
--delete from tblNote

--DELETE FROM tblAddress
